name: Publish Docker image
on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: ghcr.io
          repository: rascoro1/dev-utils
          tag_with_ref: true

  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: us.gcr.io/${{ secrets.PROJECT_ID }}/dev-utils

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD }}
          export_default_credentials: true

      # Build docker image
      - name: Image
        run: |-
          docker build -t $DOCKER_TAG .

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q

      - name: Push to GCR
        run: |-
          docker push $DOCKER_TAG

      - name: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          region: us-east1
          image: $DOCKER_TAG
          service: dev-utils
          credentials: ${{ secrets.GCLOUD }}
