name: Publish Docker image
on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: ghcr.io
          repository: rascoro1/dev-utils
          tag_with_ref: true

  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD }}
          export_default_credentials: true

      - name: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: us.gcr.io/${{ secrets.PROJECT_ID }}/dev-utils
          service: dev-utils
          credentials: ${{ secrets.GCLOUD }}
